### ISSUE TITLE
Credits and License

### ISSUE THREAD

**Issue by gvekony** [xiaohuyz/uvm-verfication-for-vs-code#2]
If you managed to _"borrow"_ my SystemVerilog syntax definitions, language configurations word by word and extension as a whole, at least give credit or put in a link with the original repository...

**Comment by xiaohuyz** [comment]
I am sorry. I made the extension only because i want to change some snippets in your extension which will not be covered because of updating, I will add your link. Sorry.

**Comment by gvekony** [comment]
Thank you! Using parts of my code is perfectly fine as the MIT license allows you to _use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software_, I just think it is good practice to either fork the original project (thus linking it, making the original development history available) or giving a link or note to the original source. No hard feelings from my side! :)

**Comment by xiaohuyz** [comment]
> If you managed to _"borrow"_ my SystemVerilog syntax definitions, language configurations word by word and extension as a whole, at least give credit or put in a link with the original repository...



> If you managed to _"borrow"_ my SystemVerilog syntax definitions, language configurations word by word and extension as a whole, at least give credit or put in a link with the original repository...

i also unpublished the extension from makret.
